=== champix56/xmlbr1-2022-10-25/client.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2011 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ville" type="xs:string"/>
	<xs:element name="rs">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			 
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="destinataire" type="xs:string"/>
	<xs:element name="cp" type="xs:string"/>
	<xs:element name="clients">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="client" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="client">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="rs" minOccurs="0"/>
				<xs:element ref="destinataire"/>
				<xs:element ref="adr1"/>
				<xs:element ref="adr2"/>
				<xs:element ref="cp"/>
				<xs:element ref="ville"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="id" type="xs:short" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="adr2">
		<xs:complexType/>
	</xs:element>
	<xs:element name="adr1" type="xs:string"/>
</xs:schema>

=== champix56/xmlbr1-2022-10-25/clients.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="test.xsl"?>

<clients xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="client.xsd">
	<client id="234" type="ets">
		<rs>Mr people</rs>
		<destinataire>Pierre Pol</destinataire>
		<adr1>rue george</adr1>
		<adr2/>
		<cp>91234</cp>
		<ville>Ville la ville</ville>
	</client>
	<client type="ets" id="654"><rs>Boby &amp; Co</rs>
		<destinataire>Boby</destinataire>
		<adr1></adr1>
		<adr2></adr2>
		<cp></cp>
		<ville></ville>
	</client>
	<client id="123" type="particulier">
		<destinataire>jean rostremer</destinataire>
		<adr1>chemin de l'homme dormant</adr1>
		<adr2/>
		<cp>54230</cp>
		<ville>Nancy Lest</ville>
	</client>
	<client id="132" type="particulier">
		<destinataire>Richard rostremer</destinataire>
		<adr1>rue de la gare</adr1>
		<adr2/>
		<cp>61210</cp>
		<ville>Sommevillet</ville>
	</client>
</clients>
